name: Update Readme

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Python Script
        run: ./README.sh



